package frontend.ui;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;

import controlP5.Button;
import controlP5.CallbackEvent;
import controlP5.CallbackListener;
import controlP5.Group;
import frontend.Main;

public class FileOpenerWithButtonUi extends FileOpenerTextfieldUI {
	
	transient private Button confirmButton;
	private String dataPath;
	
	public FileOpenerWithButtonUi(String defaultFile) {
		super(defaultFile);
		this.dataPath = Main.instance().sketchPath() + "/data/";
	}
	
	
	@Override
	public void createUI(String id, String label, int localx, int localy, int w, Group g) {
		super.createUI(id, label, localx, localy, w, g);
		
		this.confirmButton = cp5.addButton(id + "/open_file")
		.setPosition(localx, localy+35)
		.setHeight(defaultHeight)
		.setSize(w, (int) (font_size * 1.25))
		.setValue(0)
		.setLabel("open file")
		.onPress(buttonCallback())
		.setGroup(g);
	}
	
	public CallbackListener buttonCallback() {
		return new CallbackListener() {
			public void controlEvent(CallbackEvent theEvent) {
				open_file();
			}
		};
	}
	
	void open_file() {
		File f = new File(dataPath  + filename);
		
		try {
			if (!f.exists()) {
				f.createNewFile();
				write_in_new_file();
			}
			
			System.out.println("opening js file " + f);
			java.awt.Desktop.getDesktop().edit(f);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	
	void write_in_new_file() {
		String fn = dataPath + filename;
		
		try {
			BufferedWriter writer = new BufferedWriter(new FileWriter(fn));
			
			writer.write("/************************************************** \n"
					+ "** SCRIPT AUTOMATICALLY GENERATED BY ZENSTATES **** \n"
					+ "*************************************************** \n" + "*** created in: " + LocalDateTime.now()
					+ "***************************************************/ \n\n"
					+ "//you can directly get values from the blackboard... \n"
					+ "//print ('my mouseX is ' + mouseX); \n"
					+ "//and similarly you can set new values on the blackboard as follows... \n"
					+ "//blackboard.put(\"my_js_example\", example); \n");
			
			writer.flush();
			writer.close();
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
